services:
  db:
    image: postgres:15.3
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  
  backend:
    build:
      context: ./itacasa-backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    depends_on:
      - db